### ISSUE TITLE
Aggregating files with different attributes 

### ISSUE THREAD

**Issue by cornelius-agrippa** [Reading-eScience-Centre/ncwms#13] opened 2017-10-12 16:33 UTC
Hello,

I'm trying to aggregate a large group of .nc files, that although they share the same variable for time (a double time), the attributes vary slightly from file to file. To show what I mean, here's an ncdump of the variable in question between 2 files:

file1.nc
```
variables:
        double time(time) ;
                time:long_name = "time" ;
                time:standard_name = "time" ;
                time:units = "hours since 2016-12-19T00:00:00" ;
                time:calendar = "gregorian" ;
```

file2.nc
```
variables:
        double time(time) ;
                time:long_name = "time" ;
                time:standard_name = "time" ;
                time:units = "hours since 2016-12-20T00:00:00" ;
                time:calendar = "gregorian" ;
```

Sadly, because `time:units` changes between every file I'm unable to aggregate these files, which makes sense, as described by the error: `Trying to aggregate NetCDF files, but the variable time in the file /var/thredds/content/public/test/file2.nc has an attribute units with the value hours since 2016-12-20T00:00:00 which is different to the value of units on time in a different file. This variable attribute must match across all files in the aggregation.`

I'm currently migrating a ncWMS 1 application to latest version, and this seems to actually work well in version 1. Was it more permissive with attributes before? Is there a way to allow the application to be more liberal with variable's attributes?

Thank you,
Best regards

**Comment by guygriffiths** [comment] 2017-10-13 09:27
It wasn't so much that ncWMS 1.x was more permissive with attributes, it was that it handled all of the time aggregation manually, whereas ncWMS 2 uses the NcML aggregation from the Unidata NetCDF-Java libraries, which did not correctly aggregate time axes with different units.

However, I've just checked to see whether this is still the case, and it's not!  If I remove the constraint then aggregation works fine.  I think this is a fix in their latest 5.0.0 libraries.  Anyway, I'm happy to say that yes, we can be more liberal with variables' attributes!

It'll take me a little while to sort out which other attributes we can relax constraints on etc., but I'll have it in the development branch later today.  If you're happy building from source, then look for a commit later today in the `develop` branch and go from there.  If not, just ping me an email at guy.griffiths@the-iea.org and we can sort something out.

**Comment by cornelius-agrippa** [comment] 2017-10-13 15:42
Awesome, that's great news! I should be ok building from source. Thank you!

**Comment by cornelius-agrippa** [comment] 2017-10-13 17:04
Ok I've been able to build it from source and seems to accept the aggregation. However it seems to be having some trouble loading it into a dataset? I get the following error:

```
Stack trace:
uk.ac.rdg.resc.edal.exceptions.EdalException: Problem creating dataset local_101 at /var/thredds/content/public/test/*.nc
uk.ac.rdg.resc.edal.dataset.cdm.CdmDatasetFactory.createDataset(CdmDatasetFactory.java:115)
uk.ac.rdg.resc.edal.dataset.cdm.CdmDatasetFactory.createDataset(CdmDatasetFactory.java:1)
uk.ac.rdg.resc.edal.catalogue.jaxb.DatasetConfig.createDataset(DatasetConfig.java:254)
uk.ac.rdg.resc.edal.catalogue.jaxb.DatasetConfig.refresh(DatasetConfig.java:213)
uk.ac.rdg.resc.edal.catalogue.jaxb.CatalogueConfig$1.run(CatalogueConfig.java:154)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

Caused by:
java.lang.NullPointerException
ucar.nc2.ft.fmrc.FmrcDataset.getBest(FmrcDataset.java:172)
ucar.nc2.ft.fmrc.Fmrc.getDatasetBest(Fmrc.java:180)
uk.ac.rdg.resc.edal.dataset.cdm.NetcdfDatasetAggregator.getDataset(NetcdfDatasetAggregator.java:509)
uk.ac.rdg.resc.edal.dataset.cdm.CdmDatasetFactory.getNetcdfDatasetFromLocation(CdmDatasetFactory.java:123)
uk.ac.rdg.resc.edal.dataset.cdm.CdmDatasetFactory.createDataset(CdmDatasetFactory.java:83)
uk.ac.rdg.resc.edal.dataset.cdm.CdmDatasetFactory.createDataset(CdmDatasetFactory.java:1)
uk.ac.rdg.resc.edal.catalogue.jaxb.DatasetConfig.createDataset(DatasetConfig.java:254)
uk.ac.rdg.resc.edal.catalogue.jaxb.DatasetConfig.refresh(DatasetConfig.java:213)
uk.ac.rdg.resc.edal.catalogue.jaxb.CatalogueConfig$1.run(CatalogueConfig.java:154)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)
```

Did I mis-configure the dataset? Since it's an almost direct port from ncWMS1, could have made some mistake, but it seems ok:
```
<dataset id="local_101" title="Aggregation Test" location="/var/thredds/content/public/test/*.nc" queryable="true" downloadable="false" dataReaderClass="" disabled="false" updateInterval="720">
    <variables>
        <variable id="Tp" title="Sea surface wave period at variance spectral density maximum" palette="rainbow" belowMinColor="#FF000000" aboveMaxColor="#FF000000" noDataColor="transparent" numColorBands="250" disabled="false" colorScaleRange="-0.0 25.0" scaling="linear"/>
        <variable id="Dp" title="Sea surface wave direction at variance spectral density maximum" palette="rainbow" belowMinColor="#FF000000" aboveMaxColor="#FF000000" noDataColor="transparent" numColorBands="250" disabled="false" colorScaleRange="-0.0 360.0" scaling="linear"/>
    </variables>
</dataset>
```

**Comment by guygriffiths** [comment] 2017-10-16 14:27
That looks fine (although there's no need to list the variables - they'll get added automatically on the first load).  Are the files publicly available?  Or can you send them to me?

**Comment by cornelius-agrippa** [comment] 2017-10-19 09:45
Excuse my late reply.

I have a feeling this is happening because of data overlap in the time unit. Each NetCDF file that I'm trying to aggregate contains forecast data for the next 6 days, and there's new NetCDF files each day. So when I try to aggregate them, there's overlap. 

I.E.: I have a file named 20161219_0000.nc which contains forecast data from 2016-12-19 to 25-12-2016. The next day I have a 20161220_0000.nc which contains new forecast data from 2016-12-20 to 26-12-2016. There will be overlap of data between 2016-12-20 and 2016-12-25.

To confirm this I used NetcdfSubset (that comes with a [THREDDS](http://www.unidata.ucar.edu/software/thredds/current/tds/)), to trim the .nc files to contain data for only 1 day, and sure enough, it aggregates them correctly!

How would you recommend I do this? I was thinking of doing some data-patching and only have .nc files with the latest latest info (if there's overlap). Could there be an easier way to configure this? How did ncWMS 1 deal with it?

The files are not publicly available. Sadly I'll have to send them to you only tomorrow morning. Should I send to the email you mentioned before?

Best regards.

**Comment by guygriffiths** [comment] 2017-10-20 10:34
@cornelius-agrippa - Thanks for the data you sent.  Unfortunately(?) I can't reproduce the error you're having - it works perfectly.  The time overlap shouldn't be a problem, ncWMS2 uses the best timeseries - i.e. the data from `20161219_0000.nc` up to the overlap, and then `20161220_0000.nc` for the rest of it.  However, it is in that section of the code that you're getting the `NullPointerException`, so something strange is going on.

I've uploaded a build of the development version here:
http://www.personal.rdg.ac.uk/~qx901922/ncWMS2.war

Delete (or more likely, move) your config file, try that WAR and configure it through the admin interface.  The path you showed in the earlier post looked fine, aggregation should work like that.  Let me know how you get on with it.

**Comment by cornelius-agrippa** [comment] 2017-10-25 10:12
The problem here was probably between my chair and the keyboard, because it's working fine now, with a fresh Tomcat setup, both your war and the one I compiled work nicely.

I should have mentioned my setup too. I'm using openjdk 1.8.0_131 with Apache Tomcat 8.5.

**Comment by guygriffiths** [comment] 2017-10-25 10:17
Well it's not an error I've come across before, it looks like something odd was going on, but I'm not sure what.  Let me know if you come across it again.  I'll close this issue once I do a release with this code in.

**Comment by cornelius-agrippa** [comment] 2017-10-25 10:23
Will do. I'm trying to re-triggered the error, but it really wants to work correctly now 😄. 

Thank you and Best regards.

**Comment by guygriffiths** [comment] 2018-01-15 11:29
This should all be working in the latest release.  Closing

**Closed by guygriffiths** 2018-01-15 11:29 UTC
